version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: quarkus_postgres
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./DATA:/var/lib/postgresql/data
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - quarkus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: quarkus_adminer
    ports:
      - "8081:8080"
    networks:
      - quarkus-network
    depends_on:
      - postgres

  quarkus-app:
    build: .
    container_name: simple-quarkus-app
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_LOG_LEVEL=INFO
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/inventory_db
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
    networks:
      - quarkus-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  quarkus-network:
    driver: bridge
